"""local_production_upgrade_v1

Revision ID: 9a0a8f177027
Revises: 8629bc78c047
Create Date: 2026-04-04 08:13:35.214778
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '9a0a8f177027'
down_revision: Union[str, None] = '8629bc78c047'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_overrides',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('rpm_limit', sa.Integer(), nullable=True),
    sa.Column('prompt_limit', sa.Integer(), nullable=True),
    sa.Column('seat_limit', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id')
    )
    op.create_table('eval_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('version_id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('eval_type', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('criteria', sa.JSON(), nullable=True),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('issues', sa.JSON(), nullable=True),
    sa.Column('suggestions', sa.JSON(), nullable=True),
    sa.Column('test_input', sa.Text(), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('ran_by_id', sa.String(), nullable=True),
    sa.Column('ran_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ran_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['prompt_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('serve_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('api_key_id', sa.String(), nullable=False),
    sa.Column('prompt_id', sa.String(), nullable=False),
    sa.Column('version_id', sa.String(), nullable=True),
    sa.Column('environment_id', sa.String(), nullable=True),
    sa.Column('outcome', sa.String(length=20), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('llm_latency_ms', sa.Integer(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('served_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['prompt_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # NEW: Promotion Requests (re-added correctly)
    op.create_table('promotion_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('prompt_id', sa.String(), nullable=False),
    sa.Column('source_env_id', sa.String(), nullable=False),
    sa.Column('target_env_id', sa.String(), nullable=False),
    sa.Column('version_num', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_by_id', sa.String(), nullable=False),
    sa.Column('approved_by_id', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_env_id'], ['environments.id'], ),
    sa.ForeignKeyConstraint(['target_env_id'], ['environments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    with op.batch_alter_table('environments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eval_required', sa.Boolean(), nullable=True))

    with op.batch_alter_table('eval_keys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    with op.batch_alter_table('org_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invited_by_id', sa.String(), nullable=True))
        batch_op.create_foreign_key('fk_member_invited_by', 'users', ['invited_by_id'], ['id'])

    with op.batch_alter_table('organisations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_seat_limit', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('plan_prompt_limit', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('plan_rpm_limit', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('lemon_order_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('billing_email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.create_unique_constraint('uq_project_org_name', ['org_id', 'name'])

    with op.batch_alter_table('prompt_versions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_model', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('target_provider', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('override_eval', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=False, server_default='1'))
        batch_op.create_foreign_key('fk_prompt_live_version', 'prompt_versions', ['live_version_id'], ['id'], use_alter=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_login_at')

    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_prompt_live_version', type_='foreignkey')
        batch_op.drop_column('version')

    with op.batch_alter_table('prompt_versions', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('override_eval')
        batch_op.drop_column('target_provider')
        batch_op.drop_column('target_model')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint('uq_project_org_name', type_='unique')
        batch_op.drop_column('description')

    with op.batch_alter_table('organisations', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('billing_email')
        batch_op.drop_column('lemon_order_id')
        batch_op.drop_column('plan_rpm_limit')
        batch_op.drop_column('plan_prompt_limit')
        batch_op.drop_column('plan_seat_limit')

    with op.batch_alter_table('org_members', schema=None) as batch_op:
        batch_op.drop_constraint('fk_member_invited_by', type_='foreignkey')
        batch_op.drop_column('invited_by_id')

    with op.batch_alter_table('eval_keys', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('environments', schema=None) as batch_op:
        batch_op.drop_column('eval_required')

    op.drop_table('promotion_requests')
    op.drop_table('serve_events')
    op.drop_table('eval_results')
    op.drop_table('plan_overrides')
    # ### end Alembic commands ###
